a = 7
b = 4
print( a ,"+", b, "=", a + b)
print( a ,"-", b, "=", a - b)
print( a ,"/", b, "=", a / b)
print( a ,"%", b, "=", a % b)
print( a ,"*", b, "=", a * b)
print( a ,"**", b, "=", a ** b)
print( a ,"//", b, "=", a // b)